### ISSUE TITLE
Couldn't find preset stage-2

### ISSUE THREAD

**Issue by neanderthil** [BrockReece/vue-kanban#18]
Installed via npm. When trying to load component I get an error when building via npm:

ERROR in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-kanban/src/components/Kanban.vue
**Module build failed: Error: Couldn't find preset "stage-2" relative to directory** "/srv/http/productionboard/node_modules/vue-kanban"
    at /srv/http/productionboard/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/srv/http/productionboard/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/srv/http/productionboard/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/srv/http/productionboard/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/srv/http/productionboard/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/srv/http/productionboard/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/srv/http/productionboard/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/srv/http/productionboard/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/srv/http/productionboard/node_modules/babel-loader/lib/index.js:50:20)
    at /srv/http/productionboard/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/srv/http/productionboard/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)
 @ ./node_modules/vue-kanban/src/components/Kanban.vue 4:21-346
 @ ./node_modules/vue-kanban/src/plugin.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

**Comment by neanderthil** [comment]
I was missing a dependency.

npm install --save-dev babel-preset-stage-2
